<?php

namespace App\Filament\Concerns;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

/**
 * Maps Filament's resource authorization hooks onto the spatie permission
 * names generated by RolesAndPermissionsSeeder (e.g. "view_any_appointment").
 *
 * A resource picks its key in one of two ways:
 *   protected static ?string $permissionKey = 'appointment';   // property, or
 *   protected static function permissionKey(): string { ... }  // method override
 *
 * With neither, the key is derived from the model's snake_case basename.
 */
trait HasResourcePermissions
{
    protected static function permissionKey(): string
    {
        if (property_exists(static::class, 'permissionKey') && isset(static::$permissionKey)) {
            return static::$permissionKey;
        }

        return Str::snake(class_basename(static::getModel()));
    }

    protected static function hasResourceAbility(string $ability): bool
    {
        $user = Auth::user();

        return $user !== null && $user->can($ability.'_'.static::permissionKey());
    }

    public static function canViewAny(): bool
    {
        return static::hasResourceAbility('view_any');
    }

    public static function canView(Model $record): bool
    {
        return static::hasResourceAbility('view');
    }

    public static function canCreate(): bool
    {
        return static::hasResourceAbility('create');
    }

    public static function canEdit(Model $record): bool
    {
        return static::hasResourceAbility('update');
    }

    public static function canDelete(Model $record): bool
    {
        return static::hasResourceAbility('delete');
    }

    public static function canDeleteAny(): bool
    {
        return static::hasResourceAbility('delete');
    }
}
