<?php

namespace App\Filament\Concerns;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

/**
 * Maps Filament's resource authorization hooks onto the spatie permission
 * names generated by RolesAndPermissionsSeeder (e.g. "view_any_appointment").
 *
 * A resource using this trait must define:
 *   protected static string $permissionKey = 'appointment';
 */
trait HasResourcePermissions
{
    protected static function hasResourceAbility(string $ability): bool
    {
        $user = Auth::user();

        return $user !== null && $user->can($ability.'_'.static::$permissionKey);
    }

    public static function canViewAny(): bool
    {
        return static::hasResourceAbility('view_any');
    }

    public static function canView(Model $record): bool
    {
        return static::hasResourceAbility('view');
    }

    public static function canCreate(): bool
    {
        return static::hasResourceAbility('create');
    }

    public static function canEdit(Model $record): bool
    {
        return static::hasResourceAbility('update');
    }

    public static function canDelete(Model $record): bool
    {
        return static::hasResourceAbility('delete');
    }

    public static function canDeleteAny(): bool
    {
        return static::hasResourceAbility('delete');
    }
}
