<?php

namespace App\Filament\Resources;

use App\Filament\Concerns\HasResourcePermissions;
use App\Filament\Resources\ReminderResource\Pages;
use App\Models\Reminder;
use App\Services\ReminderDispatcher;
use Filament\Forms;
use Filament\Notifications\Notification;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

class ReminderResource extends Resource
{
    use HasResourcePermissions;

    protected static ?string $model = Reminder::class;

    protected static ?string $navigationIcon = 'heroicon-o-bell-alert';

    protected static ?string $navigationGroup = 'Calendar';

    protected static ?int $navigationSort = 3;

    public static function canCreate(): bool
    {
        return false; // reminders are generated by `reminders:generate`
    }

    public static function getNavigationBadge(): ?string
    {
        return (string) Reminder::pending()->whereDate('due_on', '<=', now()->addWeek())->count() ?: null;
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('due_on')->date('d M Y')->sortable(),
                Tables\Columns\TextColumn::make('category')->badge()
                    ->formatStateUsing(fn (string $state) => Reminder::CATEGORIES[$state] ?? $state)
                    ->colors(['success' => 'vaccination', 'warning' => 'desexing', 'info' => 'phone']),
                Tables\Columns\TextColumn::make('reminderType.name')->label('Type'),
                Tables\Columns\TextColumn::make('patient.name')->label('Patient')->searchable(),
                Tables\Columns\TextColumn::make('client.full_name')->label('Client')->searchable(['surname']),
                Tables\Columns\TextColumn::make('client.mobile_phone')->label('Mobile')->toggleable(),
                Tables\Columns\TextColumn::make('client.email')->label('Email')->toggleable(),
                Tables\Columns\TextColumn::make('status')->badge()
                    ->colors(['gray' => 'pending', 'success' => 'sent', 'info' => 'done', 'danger' => 'cancelled']),
                Tables\Columns\TextColumn::make('sent_channel')->label('Sent via')->badge()->toggleable(),
            ])
            ->defaultSort('due_on')
            ->filters([
                Tables\Filters\SelectFilter::make('category')->options(Reminder::CATEGORIES),
                Tables\Filters\SelectFilter::make('status')
                    ->options(['pending' => 'Pending', 'sent' => 'Sent', 'done' => 'Done', 'cancelled' => 'Cancelled'])
                    ->default('pending'),
                Tables\Filters\SelectFilter::make('species_id')->relationship('species', 'name')->label('Species'),
                Tables\Filters\Filter::make('due_on')->form([
                    Forms\Components\DatePicker::make('from')->default(now()),
                    Forms\Components\DatePicker::make('until')->default(now()->addWeeks(2)),
                ])->query(fn (\Illuminate\Database\Eloquent\Builder $query, array $data) => $query
                    ->when($data['from'] ?? null, fn ($q, $d) => $q->whereDate('due_on', '>=', $d))
                    ->when($data['until'] ?? null, fn ($q, $d) => $q->whereDate('due_on', '<=', $d))),
            ])
            ->actions([
                Tables\Actions\Action::make('markDone')->icon('heroicon-m-check')->color('success')
                    ->visible(fn (Reminder $r) => $r->status !== 'done')
                    ->action(fn (Reminder $r) => $r->update(['status' => 'done'])),
                Tables\Actions\Action::make('cancel')->icon('heroicon-m-x-mark')->color('gray')
                    ->visible(fn (Reminder $r) => $r->status === 'pending')
                    ->action(fn (Reminder $r) => $r->update(['status' => 'cancelled'])),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\BulkAction::make('send')
                        ->label('Send selected')->icon('heroicon-m-paper-airplane')
                        ->form([
                            Forms\Components\Select::make('channel')->required()->default('email')
                                ->options(['letter' => 'Letter', 'email' => 'Email', 'sms' => 'SMS']),
                        ])
                        ->action(function ($records, array $data) {
                            abort_unless(auth()->user()->can('run_reminders'), 403);
                            [$issued, $sent] = app(ReminderDispatcher::class)->sendPatientReminders($records, $data['channel']);
                            Notification::make()
                                ->title("{$sent} of {$issued} eligible reminder(s) sent by {$data['channel']}")
                                ->success()->send();
                        })
                        ->deselectRecordsAfterCompletion(),
                    Tables\Actions\BulkAction::make('markDone')->label('Mark done')->icon('heroicon-m-check')
                        ->action(fn ($records) => $records->each->update(['status' => 'done']))
                        ->deselectRecordsAfterCompletion(),
                ]),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListReminders::route('/'),
        ];
    }
}
